#!/usr/bin/env python

"""Create puzzle from input image.

This module loads image and creates puzzle by dividing image
into square pieces and then shuffles pieces to produce random puzzle.

Note that created puzzle size may differ from original image size
depending on given piece size.

"""
import numpy as np
import cv2
import random

from gaps import image_helpers

def create_puzzle(image_path, output_path, rows,columns):
    """Creates jigsaw puzzle from input image"""
    image = cv2.imread(image_path)
    pieces, piece_size = image_helpers.flatten_image(image, rows, columns)

    # Randomize pieces in order to make puzzle
    np.random.shuffle(pieces)
    sta=ImgRandom(rows*columns)
    pieces=ImRotate(pieces,sta,piece_size)
    # Create puzzle by stacking pieces
    puzzle = image_helpers.assemble_image(pieces, rows, columns)

    cv2.imwrite(output_path, puzzle)

#断片画像をランダムに回転
def ImgRandom(piece_num):
    angle=90.0
    sta=[]
    sta=[float(angle*random.randint(0,3)) for i in range(piece_num)]
    #一番左上の断片画像は回転しない
    sta[0]=0
    return sta

def ImRotate(pieces,sta,piece_size):
    center=(int(piece_size/2),int(piece_size/2))

    for i in range(len(sta)):
        trans=cv2.getRotationMatrix2D(center,sta[i],1.0)
        pieces[i]=cv2.warpAffine(pieces[i],trans,(piece_size,piece_size))

    return pieces

if __name__ == "__main__":
    image_path="D:/procon32/procon_image/test_image/island.jpg"
    output_path="D:/procon32/procon_image/puzzle_image/puzzle.jpg"
    rows=5
    columns=8
    create_puzzle(image_path,output_path,rows,columns)
